### ISSUE TITLE
`this.sizes.height` is not updated yet.

### ISSUE THREAD

**Issue by vinzdef** [okiba-gang/okiba-components#2]
https://github.com/okiba-gang/okiba-components/blob/2bf5ebaa13c33ae6eaada0073c3c565e2c9f2cd9/packages/scroll-container/index.js#L63

Dirty fix: `SizesCache.onResize()`

**Comment by lavolpecheprogramma** [comment]
Are you sure about it? it seems to works fine here https://okiba-gang.github.io/okiba-components/smooth-scroll/full-page.html
