### ISSUE TITLE
Always trigger, because now progress is capped at 0.

### ISSUE THREAD

**Issue by vinzdef** [okiba-gang/okiba-components#3]
https://github.com/okiba-gang/okiba-components/blob/2bf5ebaa13c33ae6eaada0073c3c565e2c9f2cd9/packages/view-progress/index.js#L73

Dirty fix: `const isInside = progress > 0 && progress <= 1`

**Comment by lavolpecheprogramma** [comment]
https://github.com/okiba-gang/okiba-components/blob/master/packages/view-progress/index.js#L72

Values are mapped and not capped so the value can be minor of 0 and major of 1 ;)

You can see that it works fine here (it remove correctly the css class) ;)

**Comment by lavolpecheprogramma** [comment]
https://okiba-gang.github.io/okiba-components/view-progress.html
